# Generated by Django 4.0.5 on 2024-07-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=25565),
        ),
    ]
