# Generated by Django 4.0.5 on 2024-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_alter_server_ip_alter_server_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ip',
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
