# Generated by Django 4.0.5 on 2024-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_remove_server_ip_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_properties',
            field=models.TextField(blank=True, default='#Minecraft server properties\n#Wed Jul 10 19:30:06 UTC 2024\ngenerator-settings=\nop-permission-level=4\nallow-nether=true\nlevel-name=world\nenable-query=false\nallow-flight=true\nannounce-player-achievements=true\nserver-port=25566\nlevel-type=DEFAULT\nenable-rcon=false\nforce-gamemode=false\nlevel-seed=\nserver-ip=\nmax-build-height=256\nspawn-npcs=true\nwhite-list=false\nspawn-animals=true\nhardcore=false\nsnooper-enabled=true\nonline-mode=false\nresource-pack=\npvp=true\ndifficulty=1\nenable-command-block=false\ngamemode=0\nplayer-idle-timeout=0\nmax-players=5\nspawn-monsters=true\ngenerate-structures=true\nview-distance=10\nmotd=A Minecraft Server\n', null=True),
        ),
    ]
