# Generated by Django 5.1.15 on 2026-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_server_server_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='jar_template',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
