# Generated by Django 5.1.15 on 2026-07-17 19:05

import os

import psutil
from django.conf import settings
from django.db import migrations, models

from mcmanager.console.services.provisioning import generate_rcon_credentials, rewrite_properties


def _is_server_running_pre_phase2(server_id):
    pid_file = f'/tmp/minecraft_server_{server_id}.pid'
    if not os.path.exists(pid_file):
        return False
    try:
        with open(pid_file, 'r') as f:
            pid = int(f.read().strip())
        return psutil.pid_exists(pid)
    except (ValueError, OSError):
        return False


def backfill_rcon_credentials(apps, schema_editor):
    Server = apps.get_model('console', 'Server')
    for server in Server.objects.all():
        if _is_server_running_pre_phase2(server.id):
            print(f"[!] Skipping RCON backfill for server {server.id} ({server.name}): "
                  f"it's currently running. Re-run this migration after stopping it.")
            continue
        rcon_port, rcon_password = generate_rcon_credentials(server)
        properties_path = settings.SERVERS_DIR / f'server_{server.id}' / 'server.properties'
        if properties_path.exists():
            rewrite_properties(properties_path, {
                'enable-rcon': 'true',
                'rcon.port': rcon_port,
                'rcon.password': rcon_password,
                'rcon.bind': '127.0.0.1',
            })
            server.server_properties = properties_path.read_text(encoding='utf-8', errors='ignore')
        server.rcon_port = rcon_port
        server.rcon_password = rcon_password
        server.save(update_fields=['rcon_port', 'rcon_password', 'server_properties'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_alter_server_jar_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='rcon_password',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='server',
            name='rcon_port',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_rcon_credentials, noop_reverse),
    ]
