# Generated by Django 5.1.15 on 2026-07-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_server_rcon_password_server_rcon_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
    ]
