# Generated by Django 5.1.15 on 2026-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='auto_restart_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='consecutive_restart_failures',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='server',
            name='desired_running',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='server',
            name='last_scheduled_backup_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='scheduled_backup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
