"""
Django settings for mcmanager project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("MCMANAGER_DEBUG", "False").lower() in ("true", "1", "yes")

# Determine user data directory (defaults to ~/.mcmanager, or project root in dev mode)
if os.environ.get("MCMANAGER_DATA_DIR"):
    USER_DATA_DIR = Path(os.environ["MCMANAGER_DATA_DIR"]).resolve()
else:
    is_dev = os.environ.get("MCMANAGER_DEV", "False").lower() in ("true", "1", "yes")
    if is_dev:
        USER_DATA_DIR = BASE_DIR
    else:
        USER_DATA_DIR = Path.home() / ".mcmanager"

USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
(USER_DATA_DIR / "servers").mkdir(exist_ok=True)
(USER_DATA_DIR / "jar").mkdir(exist_ok=True)
(USER_DATA_DIR / "configs").mkdir(exist_ok=True)
(USER_DATA_DIR / "run").mkdir(exist_ok=True)
(USER_DATA_DIR / "backups").mkdir(exist_ok=True)

JAR_DIR = USER_DATA_DIR / 'jar'
SERVERS_DIR = USER_DATA_DIR / 'servers'
CONFIGS_DIR = USER_DATA_DIR / 'configs'
RUN_DIR = USER_DATA_DIR / 'run'
BACKUPS_DIR = USER_DATA_DIR / 'backups'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_FILE = USER_DATA_DIR / '.secret_key'
if SECRET_KEY_FILE.exists():
    SECRET_KEY = SECRET_KEY_FILE.read_text(encoding="utf-8").strip()
else:
    from django.utils.crypto import get_random_string
    SECRET_KEY = get_random_string(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')
    try:
        SECRET_KEY_FILE.write_text(SECRET_KEY, encoding="utf-8")
    except Exception:
        pass

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '148.113.171.183']
else:
    allowed_hosts_env = os.environ.get("MCMANAGER_ALLOWED_HOSTS", "*")
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(",") if h.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps
    "mcmanager.console.apps.ConsoleConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mcmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': USER_DATA_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = USER_DATA_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAVA_BIN_PATH = os.environ.get("MCMANAGER_JAVA_BIN", "/usr/lib/jvm/java-8-openjdk-amd64/bin/java")

